/* auto-generated by gen_dncnn_int8.py -- int8 mixed-precision scales */
#ifndef DNCNN_INT8_SCALES_H
#define DNCNN_INT8_SCALES_H
static const float DNCNN_QUANT0     = 7.70174611f;  /* conv_first FP32 -> uint8 */
static const float DNCNN_REQUANT[3] = { 0.00282662416f, 0.00344384271f, 0.00495451228f };
static const float DNCNN_DEQUANT3   = 0.160464373f;  /* uint8 -> FP32 for conv_final */
#endif
