/* auto-generated by gen_dncnn_real.py -- REAL deepinv dncnn int8 scales */
#ifndef DNCNN_INT8_SCALES_H
#define DNCNN_INT8_SCALES_H
static const float DNCNN_QUANT0     = 110.436722f;  /* conv_first FP32 -> uint8 */
static const float DNCNN_REQUANT[18] = { 0.00800618157f, 0.00472166575f, 0.00456871837f, 0.00385189592f, 0.0058235256f, 0.00334876776f, 0.00330306776f, 0.00222812989f, 0.00216857227f, 0.00457670819f, 0.00222416152f, 0.00315160281f, 0.00279514887f, 0.00309081888f, 0.00284654833f, 0.0047301231f, 0.00263909553f, 0.00277258875f };
static const float DNCNN_DEQUANT3   = 0.000222799547f;  /* uint8 -> FP32 for conv_final */
#endif
