/*
 * Copyright (c) 2026 Marin Radić
 * SPDX-License-Identifier: Apache-2.0
 *
 * DnCNN int8 kernel for ET-SoC1 - the `dncnn` leaderboard model (config-driven).
 * TFMA = the int8 tensor fused-multiply-add engine op that runs the hidden convolutions.
 *
 *   conv_first+quantize (FP32) -> 18 hidden convs (int8 TFMA) -> dequantize+conv_final (FP32) + residual
 *
 * The network shape (layer count, per-layer in/out channels, layer kind) is a compile-time
 * descriptor (the NET[] table) and the compute primitives are reusable functions parameterized by
 * dims and SCP (the 48-line L1 scratchpad) line offsets, so the same source can build other
 * channel counts. Shipped config: DNCNN_REAL=1, CH=64, HIDDEN=18, IMG=64,
 * ACTIVE_HARTS=8 - the real deepinv dncnn_sigma2_gray model.
 *
 * Techniques used (int8 TFMA, output-channel tiling, adaptive tap-fold, word-copy activation pack,
 * batched cache evict, cacheline seam fix, multi-hart row banding, FP32 mixed-precision boundaries
 * with folded bias): docs/OPTIMIZATIONS.md.
 *
 * Board memory map (REAL): input @0x2000, output @0x10000, weight blob @0x14000; scales from the
 * generated dncnn_int8_scales_real.h. Self-attesting summary @0x1000 for the CI dump gate.
 */

#include <stdint.h>

#define ERBIUM_TENSOR_ASSERT(cond) ((void)(cond))
#include "erbium/isa/atomic.h"
#include "erbium/isa/barriers.h"
#include "erbium/isa/cacheops-umode.h"
#include "erbium/isa/hart.h"
#include "erbium/isa/tensors.h"
/* Scales header generated by scripts/gen_dncnn_real.py from the real deepinv weights. Included
 * literally (real header by default) so the CI leaderboard coverage checker sees the dependency;
 * override with -DDNCNN_SCALES_HEADER only for local experiments. */
#ifndef DNCNN_SCALES_HEADER
#include "dncnn_int8_scales_real.h"   /* generated: DNCNN_QUANT0, DNCNN_REQUANT[HIDDEN], DNCNN_DEQUANT3 */
#else
#include DNCNN_SCALES_HEADER
#endif
#include "pmc_probe.h"             /* -DDNCNN_PMC: hardware perf-counter probe (else no-op) */

extern char heap0_end[];

#define DNCNN_MAGIC 0xD3C11003u    /* CI leaderboard dump magic (score_results.py gate) */

/* ---- multi-hart config (canonical board: NUM_HARTS=16 ACTIVE_HARTS=8 BENCH_THREAD0_ONLY=1) ---- */
#ifndef ACTIVE_HARTS
#define ACTIVE_HARTS 1u
#endif
#define BENCH_FLB 2u
#define BENCH_FCC FCC_0

/* ================= network shape descriptor (the config the kernel reads) ==========
 * The net is uniform in channel count (64 in the shipped config), so a single compile-time
 * CH feeds the memory map and the SCP asserts, while the runtime table NET[] drives the layer
 * loop and the per-layer dims. The two are cross-checked at runtime in main (hart 0). To change
 * the channel count, edit NET[] and the per-layer weight-blob arithmetic; the primitives, the
 * output-channel (OC) tiling and the adaptive fold below already loop over whatever dims the
 * table supplies. */
enum layer_kind { FP32_FIRST, INT8_HIDDEN, FP32_FINAL };
struct layer_cfg { uint16_t in_ch; uint16_t out_ch; uint8_t kind; };

/* ---- tile params ----
 * Image size is a compile-time knob (default 64, the demo/board size). A SMALLER square
 * (-DDNCNN_IMG=32 or 16, still a multiple of P) shrinks the LOCAL sys-emu correctness run
 * without changing any per-tile math: output-channel tiling, adaptive tap-fold and requant
 * (requantization) are exercised per tile, so a small image verifies them identically but
 * ~(64/IMG)^2 faster. sys-emu wall time scales with TOTAL MACs (multiply-accumulates), so the
 * full 20-layer/64-channel net is impractical in sys-emu -- verify its math small locally, run
 * the full 64x64 on the BOARD (real silicon, ~seconds/tile). The numpy reference generator takes
 * the same DNCNN_IMG. */
#ifndef DNCNN_IMG
#define DNCNN_IMG 64u
#endif
#define IMG_W   (DNCNN_IMG)
#define IMG_H   (DNCNN_IMG)
#define K       3u                 /* conv is KxK                                 */
#define TAPS    (K * K)            /* 9                                           */
#define P       16u                /* spatial tile width (= FMA bcols; HW 2-bit field so <=16) */
#define OC_TILE 16u                /* output channels per accumulation pass (HW arows field so <=16) */
#define QUARTET 4u                 /* int8 input-channel (IC) packing unit (4 IC per FMA step) */

/* ---- compile-time shape (config-selectable; NET[] is built from these in main) ----
 * The shipped build sets these via build flags: -DDNCNN_CH=64 -DDNCNN_HIDDEN=18 gives
 * 20 layers / 64 channels (4 output-channel tiles, fold_taps=1).
 * CH must be a power-of-two divisor of 64 (16/32/64) so the input channels pack into whole
 * quartets and PADW*CH lands on 64B lines; HIDDEN is the number of int8 hidden layers. */
#ifndef DNCNN_CH
#define DNCNN_CH 16u
#endif
#ifndef DNCNN_HIDDEN
#define DNCNN_HIDDEN 3u
#endif
#define CH      (DNCNN_CH)         /* uniform hidden channel count (input IC = output OC = CH) */
#define HIDDEN  (DNCNN_HIDDEN)     /* number of INT8_HIDDEN layers                */
#define LAYERS  (HIDDEN + 2u)      /* conv_first + HIDDEN hidden + conv_final     */
#define NTX     (IMG_W / P)        /* tiles per row                               */

/* ---- real deepinv model mode (-DDNCNN_REAL=1) ----
 * 0 = synthetic path (int8 W0|WH|WF blob, image-128 input, edge-replicate halo (the 1-pixel conv
 *     border), no bias, no residual).
 * 1 = the real dncnn_sigma2_gray.pth (gen_dncnn_real.py): mixed blob (FP32 in_conv+bias | int8 WH |
 *     int32 hidden biases | FP32 out_conv+bias), input domain x=image/255 with ZERO padding (torch
 *     conv), per-conv bias (hidden via tensor_quant INT32_ADD_COL), residual out = x + net(x). */
#ifndef DNCNN_REAL
#define DNCNN_REAL 0
#endif

/* Padded row stride: the halo-padded width IMG_W+2=66 is rounded up so a row is a whole number
 * of 64B cache lines. This keeps any cache line from spanning two harts' bands on write-back (a
 * band is the horizontal row range a hart owns), which is the int8 cacheline seam-race
 * constraint. A row is PADW*CH bytes; we need PADW*CH % 64 == 0, i.e. PADW a multiple of
 * PADW_MULT = 64/CH (CH divides 64). Smallest such PADW >= IMG_W+2:
 *   CH=16 -> mult 4 -> 68 (68*16=1088=17 lines)
 *   CH=32 -> mult 2 -> 66 (66*32=2112=33 lines)
 *   CH=64 -> mult 1 -> 66 (66*64=4224=66 lines)
 * Cols IMG_W+2..PADW-1 are stride padding, never addressed (PAD_AT stops at col IMG_W). */
#define PADW_MULT (64u / CH)
#define PADW    (((IMG_W + 2u + PADW_MULT - 1u) / PADW_MULT) * PADW_MULT)
#define PADH    (IMG_H + 2u)
_Static_assert((PADW * CH) % 64u == 0u,
	"row stride must be a whole number of 64B cache lines so no line spans two bands");
_Static_assert(PADW >= IMG_W + 2u, "PADW must cover the halo-padded width");
#define ROW_STRIDE_BYTES 64u       /* one L1 scratchpad cache line               */

/* ---- adaptive tap-folding ----
 * Fold whole taps of one kernel ROW into a single int8 FMA. A group of f taps costs f*(IC/QUARTET)
 * quartets; the FMA acols field is 4 bits, so at most 16 quartets. Budget = 16/(IC/QUARTET) =
 * 64/IC, and the effective fold width is min(K, budget). At the shipped 64 input channels the
 * budget is 1, so each FMA folds a single tap. Folding stays within a kernel row
 * (all taps in a group share the row offset dy), so pack_b_group reads one padded row per group.
 * Each row splits into CHUNKS_PER_ROW chunks (the last possibly partial); NGRP (the number of FMA
 * dispatch groups per tile) is the total. The output is bit-identical for any grouping: the int32
 * TENC (tensor int32 accumulator) sums exactly and is associative. */
#define FOLD_BUDGET     (16u / (CH / QUARTET))                 /* =1 at CH=64 */
#define FOLD_TAPS       ((K < FOLD_BUDGET) ? K : FOLD_BUDGET)  /* =1 at CH=64 */
#define CHUNKS_PER_ROW  ((K + FOLD_TAPS - 1u) / FOLD_TAPS)     /* =3 at CH=64 */
#define NGRP            (K * CHUNKS_PER_ROW)                    /* =9 at CH=64 */
_Static_assert(FOLD_TAPS >= 1u, "must fold at least one tap");
_Static_assert(FOLD_TAPS * (CH / QUARTET) <= 16u, "folded contraction must fit acols (<=16 quartets)");

/* L1 scratchpad line allocation for one int8 tile (per hart/minion) */
#define SCP_A_LINE      0u         /* weights A: OC_TILE lines (one OC/line, fold_taps*CH bytes) */
#define SCP_B_LINE      OC_TILE    /* activations B: up to FOLD_TAPS*(CH/QUARTET) quartet lines  */
/* Requant SCP lines sit right after the B lines (line 32 at 64ch). DNCNN_REAL uses TWO consecutive
 * lines: SCP_SCALE_LINE holds the per-OC int32 bias (tensor_quant INT32_ADD_COL reads scp_loc) and
 * SCP_SCALE_LINE+1 the per-OC scale (MUL_COL reads the auto-advanced scp_loc+1; see
 * tensors.cpp:1004). The DNCNN_REAL=0 test path uses ONE line (per-OC scale only). */
#define SCP_SCALE_LINE  (SCP_B_LINE + FOLD_TAPS * (CH / QUARTET))  /* requant: bias(real)/scale line */
#define OPCODE_INT8     3u         /* tensor_fma type = int8                                     */
_Static_assert(OC_TILE <= 16u, "OC_TILE must fit a_num_rows (4-bit) and 32 FREGs (16 OC x 16 spatial)");
_Static_assert(P <= 16u, "P must fit b_num_col (2-bit) => <=16 spatial");
_Static_assert(SCP_B_LINE + FOLD_TAPS * (CH / QUARTET) <= SCP_SCALE_LINE, "B lines overlap the scale line");
_Static_assert(SCP_SCALE_LINE + DNCNN_REAL < 48u, "SCP requant line(s) exceed the 48-line L1 scratchpad");

/* Per-hart B pack (bpk, the packed activation buffer) holds every group's activations and is
 * evicted in one batch: total is TAPS*(CH/QUARTET) quartet lines regardless of how taps are
 * chunked into groups. */
#define BPK_STRIDE  (TAPS * (CH / QUARTET) * ROW_STRIDE_BYTES) /* 9216 B/hart at 64ch */
#define TEMP_STRIDE (OC_TILE * P)  /* per-hart quant output [OC][P]: 256 B (4 lines)   */
_Static_assert(BPK_STRIDE  % 64u == 0u, "BPK_STRIDE must be a whole number of 64B lines");
_Static_assert(TEMP_STRIDE % 64u == 0u, "TEMP_STRIDE must be a whole number of 64B lines");

/* Baked-in shape assumptions; assert so a wrong constant fails the build. */
_Static_assert(CH == 16u || CH == 32u || CH == 64u,
	"CH must be 16, 32, or 64 (power-of-two divisor of 64: whole IC-quartets + 64B rows)");
_Static_assert(CH % QUARTET == 0u, "CH must pack into whole IC-quartets");
_Static_assert(64u % CH == 0u,   "CH must divide 64 so PADW_MULT = 64/CH is exact");
_Static_assert(P  == 16u,        "P must be 16 (FMA bcols / one store block)");
_Static_assert(IMG_W % P == 0u,  "IMG_W must be a multiple of P");
_Static_assert(HIDDEN >= 1u,     "need at least one int8 hidden layer");

/* Hart count must fit the barrier mask (1u<<ACTIVE_HARTS) and leave every band non-empty. */
_Static_assert(ACTIVE_HARTS >= 1u && ACTIVE_HARTS <= 32u, "ACTIVE_HARTS must be in [1,32]");
_Static_assert(ACTIVE_HARTS <= IMG_H, "ACTIVE_HARTS must not exceed image rows (else empty bands)");

/* FP32 boundary scales (match the numpy reference). They are compile-time constants, so
 * these stay multiplies, never fdiv (fdiv hangs in U-mode on this platform). */
#define FIRST_SCALE (1.0f / 128.0f)
#define FINAL_SCALE (1.0f / 16.0f)

/* ---- weight blob sub-sizes ---- */
#define WH_BYTES  (HIDDEN * CH * CH * K * K)   /* int8 hidden WH[l][oc][ic][k] (both modes) */
#if DNCNN_REAL
/* mixed blob (gen_dncnn_real.py): FP32 in_conv W+b | int8 WH | int32 hidden biases |
 * FP32 out_conv W+b. Sub-offsets used in main to slice the blob. */
#define WIN_BYTES   (CH * 1u * K * K * 4u)     /* fp32 in_conv  [OC][1][ky][kx]  */
#define BIN_BYTES   (CH * 4u)                  /* fp32 in_conv bias [OC]         */
#define BHID_BYTES  (HIDDEN * CH * 4u)         /* int32 hidden biases [l][oc]    */
#define WOUT_BYTES  (1u * CH * K * K * 4u)     /* fp32 out_conv [1][IC][ky][kx]  */
#define BOUT_BYTES  (1u * 4u)                  /* fp32 out_conv bias             */
#else
#define W0_BYTES  (CH * K * K)                 /* int8 conv_first  W0[oc][ky][kx] */
#define WF_BYTES  (CH * K * K)                 /* int8 conv_final  WF[ic][ky][kx] */
#endif

/* ---- working-buffer sizes ---- */
#define IMG_BYTES     (IMG_W * IMG_H)               /* 1-channel uint8 image        */
#define ACT_BYTES     (IMG_W * IMG_H * CH)          /* NHWC uint8 activation        */
#define PAD_BYTES     (PADW * PADH * CH)            /* padded NHWC uint8            */
/* Re-arranged hidden weights, group-major: one 64B line per (group, output channel), for all CH
 * output channels (rearrange_hidden_weights indexes gidx*CH+oc), so the size is NGRP*CH lines. */
#define AW_TAP_BYTES  (NGRP * CH * ROW_STRIDE_BYTES)
#if DNCNN_REAL
#define WEIGHTS_BYTES (WIN_BYTES + BIN_BYTES + WH_BYTES + BHID_BYTES + WOUT_BYTES + BOUT_BYTES)
#else
#define WEIGHTS_BYTES (W0_BYTES + WH_BYTES + WF_BYTES)
#endif

/* ---- memory map (byte offsets from base) ----
 * INPUT (0x2000) and OUTPUT (0x10000) are fixed: the launcher --file_load's the image at INPUT and
 * the dump + check_int8_seams.py read the result at OUTPUT. WEIGHTS and every working buffer are
 * computed cumulatively above OUTPUT (64KB-aligned for the big regions) so a config's activation and
 * weight sizes drive the layout with no hand-tuning. The run script --file_load's the weight blob at
 * WEIGHTS_OFFSET. All regions are asserted non-overlapping and within the 16MB launch window. */
#define ALIGN64K(x)    (((x) + 0xFFFFu) & ~0xFFFFu)
#define SLOTS_OFFSET   0x0000u     /* per-hart attestation slots (ACTIVE_HARTS x 64B) */
#define SLOT_BYTES     64u         /* one slot = one cache line (no cross-hart sharing) */
#define SUMMARY_OFFSET 0x1000u
#define BARRIER_OFFSET 0x1800u     /* cross-hart barrier state                 */
#define INPUT_OFFSET   0x2000u     /* harness: uint8[64][64] image (PINNED)    */
#define OUTPUT_OFFSET  0x10000u    /* harness: uint8[64][64] result (PINNED)   */
#define WEIGHTS_OFFSET 0x14000u    /* harness: int8 blob W0|WH|WF (above output) */
#define QPADA_OFFSET   ALIGN64K(WEIGHTS_OFFSET + WEIGHTS_BYTES)  /* hidden ping-pong A (padded) */
#define QPADB_OFFSET   ALIGN64K(QPADA_OFFSET + PAD_BYTES)        /* hidden ping-pong B (padded) */
#define AW_TAP_OFFSET  ALIGN64K(QPADB_OFFSET + PAD_BYTES)        /* hidden weights, re-arranged */
#define MVEC_BYTES     (((CH * 4u + 63u) / 64u) * 64u)          /* per-OC scale, whole 64B lines */
#define MVEC_OFFSET    (AW_TAP_OFFSET + AW_TAP_BYTES)            /* per-OC requant scale        */
#if DNCNN_REAL
#define BVEC_OFFSET    (MVEC_OFFSET + MVEC_BYTES)                /* per-OC int32 hidden bias (real) */
#define BPACK_OFFSET   ALIGN64K(BVEC_OFFSET + MVEC_BYTES)        /* per-hart folded B pack (bpk) */
#else
#define BPACK_OFFSET   ALIGN64K(MVEC_OFFSET + MVEC_BYTES)        /* per-hart folded B pack (bpk) */
#endif
#define TEMP_OFFSET    ALIGN64K(BPACK_OFFSET + ACTIVE_HARTS * BPK_STRIDE)  /* per-hart quant out */
#define TEMP_END       ALIGN64K(TEMP_OFFSET + ACTIVE_HARTS * TEMP_STRIDE)  /* ceiling of temps  */
#ifdef DNCNN_PMC
#define PMC_OFFSET     TEMP_END    /* perf-counter dump region */
#define QDUMP_OFFSET   ALIGN64K(PMC_OFFSET + sizeof(struct pmc_region))
_Static_assert(PMC_OFFSET >= TEMP_END, "PMC region collides with per-hart temp");
_Static_assert(PMC_OFFSET + sizeof(struct pmc_region) <= QDUMP_OFFSET, "PMC region overruns into QDUMP");
#else
#define QDUMP_OFFSET   TEMP_END    /* HIDDEN+1 copies of q interiors (debug)   */
#endif
#define DUMP_END       (QDUMP_OFFSET + (HIDDEN + 1u) * ACT_BYTES)

/* All tensor-touched buffers must be 64-byte aligned (tensor_load rounds addr). */
_Static_assert(WEIGHTS_OFFSET % 64u == 0u, "weights misaligned");
_Static_assert(QPADA_OFFSET   % 64u == 0u, "qpadA misaligned");
_Static_assert(QPADB_OFFSET   % 64u == 0u, "qpadB misaligned");
_Static_assert(AW_TAP_OFFSET  % 64u == 0u, "aw_tap misaligned");
_Static_assert(MVEC_OFFSET    % 64u == 0u, "mvec misaligned");
_Static_assert(BPACK_OFFSET   % 64u == 0u, "bpk misaligned");
_Static_assert(TEMP_OFFSET    % 64u == 0u, "temp misaligned");
/* Regions must not overlap their successor (cumulative layout makes most trivially true; keep
 * them as guards against a future size/offset edit). */
_Static_assert(INPUT_OFFSET   + IMG_BYTES     <= OUTPUT_OFFSET,  "input overlaps output");
_Static_assert(OUTPUT_OFFSET  + IMG_BYTES     <= WEIGHTS_OFFSET, "output overlaps weights");
_Static_assert(WEIGHTS_OFFSET + WEIGHTS_BYTES <= QPADA_OFFSET,   "weights overlap qpadA");
_Static_assert(QPADA_OFFSET   + PAD_BYTES     <= QPADB_OFFSET,   "qpadA overlaps qpadB");
_Static_assert(QPADB_OFFSET   + PAD_BYTES     <= AW_TAP_OFFSET,  "qpadB overlaps aw_tap");
_Static_assert(AW_TAP_OFFSET  + AW_TAP_BYTES  <= MVEC_OFFSET,    "aw_tap overlaps mvec");
#if DNCNN_REAL
_Static_assert(MVEC_OFFSET + MVEC_BYTES <= BVEC_OFFSET,          "mvec overlaps bvec");
_Static_assert(BVEC_OFFSET + MVEC_BYTES <= BPACK_OFFSET,         "bvec overlaps bpk");
#else
_Static_assert(MVEC_OFFSET + MVEC_BYTES <= BPACK_OFFSET,         "mvec overlaps bpk");
#endif
_Static_assert(ACTIVE_HARTS * BPK_STRIDE  <= (TEMP_OFFSET - BPACK_OFFSET), "per-hart bpk region overflow");
_Static_assert(ACTIVE_HARTS * TEMP_STRIDE <= (TEMP_END - TEMP_OFFSET),     "per-hart temp region overflow");
_Static_assert(ACTIVE_HARTS * SLOT_BYTES <= SUMMARY_OFFSET, "attestation slots overflow into summary");
_Static_assert(DUMP_END <= 16u * 1024u * 1024u, "buffers exceed the 16MB launch region");

/* pointer to padded pixel (y,x)'s CH channels; y,x are REAL coords (-1..IMG ok) */
#define PAD_AT(pad, y, x) ((pad) + ((uint32_t)((y) + 1) * PADW + ((x) + 1)) * CH)

/* tensor_fma(tenc_loc=1) overwrites f0..f31, but GCC can't see it through the CSR
 * asm, so it may keep live FP values there - force a clobber to spill them first. */
#define FREG_CLOBBER_BARRIER() __asm__ __volatile__("" ::: "memory", \
	"f0","f1","f2","f3","f4","f5","f6","f7","f8","f9","f10","f11","f12","f13","f14","f15", \
	"f16","f17","f18","f19","f20","f21","f22","f23","f24","f25","f26","f27","f28","f29","f30","f31")

/* Build the runtime shape descriptor from CH/HIDDEN: conv_first, then HIDDEN int8 hidden layers,
 * then conv_final. Building it at runtime lets one source drive any HIDDEN count without a
 * per-config array literal. It is only read in main's per-layer dispatch (not the hot tile loop),
 * so it costs nothing on the critical path (the hot loops all use the compile-time CH). */
static void build_net(struct layer_cfg net[LAYERS])
{
	net[0].in_ch = 1u;  net[0].out_ch = CH;  net[0].kind = FP32_FIRST;
	for (uint32_t l = 1u; l <= HIDDEN; l++) {
		net[l].in_ch = CH;  net[l].out_ch = CH;  net[l].kind = INT8_HIDDEN;
	}
	net[LAYERS - 1u].in_ch = CH;  net[LAYERS - 1u].out_ch = CH;  net[LAYERS - 1u].kind = FP32_FINAL;
}

/* Each hart attests its own output band in a private 64B slot; hart 0 folds them into
 * the summary. Field order in both structs is fixed by the CI scorer (score_results.py
 * reads a "<16I" summary at SUMMARY_OFFSET and gates on magic, done_count==active_harts,
 * output_sum==slot_checksum_sum), so the layout must not be reordered. */
struct dncnn_slot {
	uint32_t magic;
	uint32_t hart_id;
	uint32_t minion_id;
	uint32_t thread_id;
	uint32_t row0;
	uint32_t row1;
	uint32_t active_harts;
	uint32_t checksum;      /* sum of this hart's output-band bytes */
	uint32_t done;
	uint32_t reserved[7];
};
_Static_assert(sizeof(struct dncnn_slot) == SLOT_BYTES, "slot must be exactly one cache line");

struct dncnn_summary {
	uint32_t magic;
	uint32_t active_harts;
	uint32_t passes;
	uint32_t width;
	uint32_t height;
	uint32_t channels;
	uint32_t layers;
	uint32_t active_mask;
	uint32_t done_count;
	uint32_t output_sum;
	uint32_t slot_checksum_sum;
	uint32_t ops_lo;
	uint32_t ops_hi;
	uint32_t tensor_error;  /* diagnostics; ignored by the scorer's reserved tail */
	uint32_t reserved[2];
};
_Static_assert(sizeof(struct dncnn_summary) == 16u * 4u, "summary must be 16 x uint32 for the CI scorer");

static uintptr_t buffer_base_from_args(uintptr_t arg_area)
{
	if (arg_area == 0u || arg_area == ~(uintptr_t)0u) {
		return (uintptr_t)heap0_end - (16u * 1024u * 1024u);
	}
	const uintptr_t ptr = *(volatile uintptr_t *)arg_area;
	if (ptr == 0u || ptr == ~(uintptr_t)0u) {
		return (uintptr_t)heap0_end - (16u * 1024u * 1024u);
	}
	return ptr;
}

/* ================= multi-hart barrier + hart-id ======== */

struct bench_barrier_state {
	uint32_t count;
	uint32_t epoch;
	uint32_t reserved[14];
};
static volatile struct bench_barrier_state *g_barrier;

static inline uint32_t active_mask_t0(void)
{
#ifdef BENCH_THREAD0_ONLY
	if (ACTIVE_HARTS >= 32u) return 0xffffffffu;
	return (1u << ACTIVE_HARTS) - 1u;
#else
	uint32_t mask = 0;
	for (uint32_t h = 0; h < ACTIVE_HARTS; h += 2u) mask |= 1u << (h >> 1);
	return mask;
#endif
}
static inline uint32_t active_mask_t1(void)
{
#ifdef BENCH_THREAD0_ONLY
	return 0u;
#else
	uint32_t mask = 0;
	for (uint32_t h = 1; h < ACTIVE_HARTS; h += 2u) mask |= 1u << (h >> 1);
	return mask;
#endif
}
static inline uint32_t bench_hart_id(void)
{
#ifdef BENCH_THREAD0_ONLY
	return get_minion_id();
#else
	return get_hart_id() & 0x3fu;
#endif
}
static inline int bench_hart_enabled(uint32_t hart_id)
{
#ifdef BENCH_THREAD0_ONLY
	return get_thread_id() == 0u && hart_id < ACTIVE_HARTS && hart_id < 32u;
#else
	return hart_id < ACTIVE_HARTS && hart_id < 16u;
#endif
}
static inline void bench_barrier(void)
{
	if (ACTIVE_HARTS > 1u) {
#ifdef BENCH_THREAD0_ONLY
		volatile struct bench_barrier_state *const barrier = g_barrier;
		const uint32_t epoch = atomic_load_local_32(&barrier->epoch);
		const uint32_t prior = atomic_add_local_32(&barrier->count, 1u);
		if (prior + 1u == ACTIVE_HARTS) {
			atomic_store_local_32(&barrier->count, 0u);
			FENCE;
			atomic_add_local_32(&barrier->epoch, 1u);
		} else {
			while (atomic_load_local_32(&barrier->epoch) == epoch) FENCE;
		}
		FENCE;
#else
		shire_barrier(BENCH_FLB, BENCH_FCC, ACTIVE_HARTS,
			      active_mask_t0(), active_mask_t1());
#endif
	}
}

/* ================= reusable tile primitives (each tensor CSR encoding lives here once) ====
 * Parameterized by dims + SCP offsets; the hot path reuses them across every group/tile. */

/* A quartet-sized copy unit: may_alias makes the word copy strict-aliasing safe across the
 * int8/uint8 buffers (a quartet is 4 contiguous, 4-aligned bytes in both). */
typedef uint32_t quartet_word __attribute__((__may_alias__));

/* Taps in the chunk starting at c. Groups are the nested (ky, c) loops with a compile-time
 * FOLD_TAPS step, which keeps the folded tap count a compile-time constant. */
#define NT_AT(c)  ((K - (c) < FOLD_TAPS) ? (K - (c)) : FOLD_TAPS)

/* Gather one group's activation windows (kernel row dy, taps kx0..kx0+n_taps-1) into the
 * quartet-interleaved B layout: line ti*(CH/QUARTET)+q holds [tap ti][quartet q], matching the
 * group's A byte order. Each input-channel quartet moves as one aligned word. CH is compile-time
 * so the strides fold and the copy stays unrolled. */
static inline void pack_b_group(int8_t *restrict bpk, const uint8_t *restrict pad,
				uint32_t y, uint32_t x0, int dy, uint32_t kx0, uint32_t n_taps)
{
	for (uint32_t ti = 0; ti < n_taps; ti++) {
		/* first spatial column of this tap's window; consecutive columns are CH bytes apart */
		const uint8_t *restrict row = PAD_AT(pad, (int)y + dy, (int)x0 + ((int)(kx0 + ti) - (int)(K / 2u)));
		for (uint32_t q = 0; q < CH / QUARTET; q++) {
			int8_t *restrict dstl = bpk + (ti * (CH / QUARTET) + q) * ROW_STRIDE_BYTES;
			const uint8_t *restrict srcq = row + q * QUARTET;
			for (uint32_t j = 0; j < P; j++)
				*(quartet_word *)(dstl + j * QUARTET) =
					*(const quartet_word *)(srcq + j * CH);
		}
	}
}

/* One group's int8 MAC in a single dispatch: oc output channels x n_taps*CH input channels x P
 * spatial. A is signed, B unsigned - mind the tensors.h operand-name swap (tenb_unsigned gates
 * A=weights, tena_unsigned gates B=activations). `first` resets the TENC accumulator; `last`
 * copies TENC into the FREGs. */
static inline void fma_group(int first, int last, uint32_t n_taps, uint32_t oc)
{
	tensor_fma(false, (P / QUARTET) - 1u, oc - 1u, n_taps * (CH / QUARTET) - 1u, 0,
		   (bool)last, false, true, false, SCP_B_LINE, SCP_A_LINE, OPCODE_INT8, (bool)first);
}

/* Fused requantization, int32 accumulator to uint8 in the FREGs: dequant, scale, round,
 * relu+clamp, pack. MUL_COL applies the per-OC scale from the loaded scale line. */
static inline void requant_u8(uint32_t scp_scale, uint32_t oc)
{
	tensor_quant(0, (P / QUARTET) - 1u, oc - 1u, scp_scale,
		     QUANT_LAST_TRANS, QUANT_LAST_TRANS, QUANT_LAST_TRANS,
		     QUANT_LAST_TRANS, QUANT_LAST_TRANS,
		     QUANT_PACK_128B, QUANT_SATUINT8, QUANT_FP32_TO_INT32,
		     QUANT_FP32_MUL_COL, QUANT_INT32_TO_FP32);
}

#if DNCNN_REAL
/* Real-model requantization: adds the per-OC int32 bias, then dequant/scale/round/relu+clamp/pack.
 * tensor_quant auto-advances the SCP line, so ADD_COL reads scp_bias and MUL_COL reads scp_bias+1
 * (the scale line). */
static inline void requant_u8_bias(uint32_t scp_bias, uint32_t oc)
{
	tensor_quant(0, (P / QUARTET) - 1u, oc - 1u, scp_bias,
		     QUANT_LAST_TRANS, QUANT_LAST_TRANS, QUANT_LAST_TRANS, QUANT_LAST_TRANS,
		     QUANT_PACK_128B, QUANT_SATUINT8, QUANT_FP32_TO_INT32,
		     QUANT_FP32_MUL_COL, QUANT_INT32_TO_FP32, QUANT_INT32_ADD_COL);
}
#endif

/* Store packed uint8 [OC][P] (rows in FREGs 0,2,4,...; one 16B block per row; P stride). */
static inline void store_u8_tile(uint8_t *dst, uint32_t oc)
{
	tensor_store(1, 0, 0, oc - 1u, (uint64_t)dst, 0, P);
}

/* Compute one hidden-layer output tile at spatial (y,x0) into the padded destination's interior. */
static void conv_tile(const uint8_t *restrict pad, const int8_t *restrict aw,
		      int8_t *restrict bpk, const float *restrict mvec,
		      const int32_t *restrict bvec,
		      uint8_t *restrict temp, uint8_t *restrict padout,
		      uint32_t y, uint32_t x0)
{
	(void)bvec;
	/* Pack every group's activations first, then evict the whole pack in one batch. Dims are
	 * compile-time (CH, NGRP, OC_TILE, FOLD_TAPS) so these loops keep constant strides and unroll. */
	uint32_t off = 0;
	for (uint32_t ky = 0; ky < K; ky++)
		for (uint32_t c = 0; c < K; c += FOLD_TAPS) {             /* chunk step is compile-time */
			const uint32_t nt = NT_AT(c);
			pack_b_group(bpk + off, pad, y, x0, (int)ky - (int)(K / 2u), c, nt);
			off += nt * (CH / QUARTET) * ROW_STRIDE_BYTES;
		}
	FENCE; evict(bpk, off); WAIT_CACHEOPS;

	for (uint32_t oc0 = 0; oc0 < CH; oc0 += OC_TILE) {                 /* one OC tile: fold TAPS into NGRP MACs, requant, store */
		const uint32_t ntile = (CH - oc0 < OC_TILE) ? (CH - oc0) : OC_TILE;
		uint32_t boff = 0, gidx = 0;
		for (uint32_t ky = 0; ky < K; ky++)
			for (uint32_t c = 0; c < K; c += FOLD_TAPS) {
				const uint32_t nt = NT_AT(c);
				const uint32_t aq = nt * (CH / QUARTET);         /* B quartet lines this group */
				tensor_load(false, false, SCP_A_LINE, 0, 0,
					    (uint64_t)(aw + ((uint64_t)gidx * CH + oc0) * ROW_STRIDE_BYTES), 0,
					    ntile - 1u, ROW_STRIDE_BYTES, 0);        /* A: ntile OC lines */
				tensor_load(false, false, SCP_B_LINE, 0, 0,
					    (uint64_t)(bpk + boff), 0,
					    aq - 1u, ROW_STRIDE_BYTES, 0);           /* B: aq quartet lines */
				tensor_wait(TENSOR_LOAD_WAIT_0);

				fma_group(/*first*/ gidx == 0u, /*last*/ gidx == NGRP - 1u, nt, ntile);
				tensor_wait(TENSOR_FMA_WAIT);
				boff += aq * ROW_STRIDE_BYTES;
				gidx++;
			}

#if DNCNN_REAL
		tensor_load(false, false, SCP_SCALE_LINE, 0, 0, (uint64_t)(bvec + oc0), 0,
			    0u, ROW_STRIDE_BYTES, 0);                        /* per-OC int32 bias   */
		tensor_load(false, false, SCP_SCALE_LINE + 1u, 0, 0, (uint64_t)(mvec + oc0), 0,
			    0u, ROW_STRIDE_BYTES, 0);                        /* per-OC requant scale */
		tensor_wait(TENSOR_LOAD_WAIT_0);
		requant_u8_bias(SCP_SCALE_LINE, ntile);  tensor_wait(TENSOR_QUANT_WAIT);
#else
		tensor_load(false, false, SCP_SCALE_LINE, 0, 0, (uint64_t)(mvec + oc0), 0,
			    0u, ROW_STRIDE_BYTES, 0);                        /* per-OC requant scale */
		tensor_wait(TENSOR_LOAD_WAIT_0);
		requant_u8(SCP_SCALE_LINE, ntile);  tensor_wait(TENSOR_QUANT_WAIT);
#endif
		store_u8_tile(temp, ntile);  tensor_wait(TENSOR_STORE_WAIT);
		FREG_CLOBBER_BARRIER();
		FENCE; evict(temp, ntile * P); WAIT_CACHEOPS;

		for (uint32_t oc = 0; oc < ntile; oc++)          /* scatter this tile into the padded interior */
			for (uint32_t j = 0; j < P; j++)
				PAD_AT(padout, y, x0 + j)[oc0 + oc] = temp[oc * P + j];
	}
}

/* Replicate-fill the 1-pixel halo around rows [row0,row1): left/right columns every row,
 * the top row when row0==0, the bottom when row1==IMG_H. layer_publish calls it once over
 * the whole image on hart 0, which owns the shared halo. */
/* Fill the 1-pixel halo. The real deepinv model uses ZERO padding (torch conv2d), so DNCNN_REAL
 * writes 0 into the halo; the DNCNN_REAL=0 test path replicates the edge pixel instead. */
#if DNCNN_REAL
#define HALO_L(pad, y)   0u
#define HALO_R(pad, y)   0u
#define HALO_T(pad, x)   0u
#define HALO_B(pad, x)   0u
#else
#define HALO_L(pad, y)   PAD_AT(pad, (int)(y), 0)[ic]
#define HALO_R(pad, y)   PAD_AT(pad, (int)(y), (int)IMG_W - 1)[ic]
#define HALO_T(pad, x)   PAD_AT(pad, 0, (x))[ic]
#define HALO_B(pad, x)   PAD_AT(pad, (int)IMG_H - 1, (x))[ic]
#endif
static void fill_halo_band(uint8_t *pad, uint32_t row0, uint32_t row1)
{
	for (uint32_t y = row0; y < row1; y++)              /* left/right columns of my rows */
		for (uint32_t ic = 0; ic < CH; ic++) {
			PAD_AT(pad, (int)y, -1)[ic]         = HALO_L(pad, y);
			PAD_AT(pad, (int)y, (int)IMG_W)[ic] = HALO_R(pad, y);
		}
	if (row0 == 0u)                                     /* top halo row + corners */
		for (int x = -1; x <= (int)IMG_W; x++)
			for (uint32_t ic = 0; ic < CH; ic++)
				PAD_AT(pad, -1, x)[ic] = HALO_T(pad, x);
	if (row1 == IMG_H)                                  /* bottom halo row + corners */
		for (int x = -1; x <= (int)IMG_W; x++)
			for (uint32_t ic = 0; ic < CH; ic++)
				PAD_AT(pad, (int)IMG_H, x)[ic] = HALO_B(pad, x);
}

/* Make this hart's band (and the halo) globally visible before the next layer reads across
 * band boundaries: evict my band, barrier, then hart 0 fills and evicts the whole halo, then
 * barrier. */
static void layer_publish(uint8_t *pad, uint32_t hart_id, uint32_t row0, uint32_t row1)
{
	FENCE;
	evict(pad + (uint64_t)(row0 + 1u) * PADW * CH, (uint64_t)(row1 - row0) * PADW * CH);
	WAIT_CACHEOPS;
	bench_barrier();
	if (hart_id == 0u) {
		fill_halo_band(pad, 0u, IMG_H);   /* whole-image halo */
		FENCE;
		evict(pad, PAD_BYTES);
		WAIT_CACHEOPS;
	}
	bench_barrier();
}

/* Invalidate this hart's read window (band +/- 1 row) so it reads neighbours' fresh
 * data from DRAM. Call RIGHT BEFORE the read (no barrier between invalidate and read). */
static void invalidate_read(const uint8_t *pad, uint32_t row0, uint32_t row1)
{
	const uint32_t rp1 = (row1 + 2u <= PADH) ? (row1 + 2u) : PADH;
	evict(pad + (uint64_t)row0 * PADW * CH, (uint64_t)(rp1 - row0) * PADW * CH);
	WAIT_CACHEOPS;
}

/* ================= FP32 boundary + quant glue (scalar; matches numpy exactly) ===== */

/* edge-replicate clamp of a coordinate into [0, lim) */
static inline int clampi(int v, uint32_t lim)
{
	if (v < 0) return 0;
	if (v >= (int)lim) return (int)lim - 1;
	return v;
}

/* round-to-nearest-even (matches numpy np.rint); no libm, no fdiv */
static inline int32_t rint_rne(float v)
{
	int32_t r;
	__asm__("fcvt.w.s %0, %1, rne" : "=r"(r) : "f"(v));
	return r;
}

/* round-half-up = floor(v + 0.5): matches conv_final's np.floor(val+0.5). rdn = round down. */
static inline int32_t round_half_up(float v)
{
	int32_t r; const float vv = v + 0.5f;
	__asm__("fcvt.w.s %0, %1, rdn" : "=r"(r) : "f"(vv));
	return r;
}

/* conv_first with the quantize folded in: uint8 image (1 channel) becomes a uint8 padded
 * activation, written straight into the interior of qpad (the halo-padded activation buffer).
 * Per output: x=img-128, KxK, times FIRST_SCALE, ReLU, times QUANT0, round-to-nearest-even,
 * clamp[0,255]. Accumulates in FP32 in the reference's tap order. */
static void conv_first_quant(const uint8_t *restrict img, const int8_t *restrict w0,
			     uint8_t *restrict qpad, float qscale,
			     uint32_t row0, uint32_t row1)
{
	for (uint32_t oc = 0; oc < CH; oc++) {   /* compile-time CH so the scalar loops unroll */
		for (uint32_t y = row0; y < row1; y++) {
			for (uint32_t x = 0; x < IMG_W; x++) {
				float acc = 0.0f;
				for (int ky = -1; ky <= 1; ky++) {
					const int yy = clampi((int)y + ky, IMG_H);
					for (int kx = -1; kx <= 1; kx++) {
						const int xx = clampi((int)x + kx, IMG_W);
						const float xv =
							(float)img[(uint32_t)yy * IMG_W + (uint32_t)xx] - 128.0f;
						acc += xv * (float)w0[oc * K * K +
								     (uint32_t)(ky + 1) * K + (uint32_t)(kx + 1)];
					}
				}
				const float o = acc * FIRST_SCALE;
				int32_t q = rint_rne((o > 0.0f ? o : 0.0f) * qscale);
				if (q < 0) q = 0; else if (q > 255) q = 255;
				PAD_AT(qpad, (int)y, (int)x)[oc] = (uint8_t)q;
			}
		}
	}
}

/* conv_final with the dequant folded in: reads the halo-filled padded uint8 activation and
 * writes the uint8 image. Per output: dequantize each input (times DEQUANT3), KxK, times
 * FINAL_SCALE, +128, round-half-up, clamp[0,255]. Neighbours come from the halo, so no
 * coordinate clamping. */
static void conv_final_dequant(const uint8_t *restrict cur, float dequant,
			       const int8_t *restrict wf, uint8_t *restrict out,
			       uint32_t row0, uint32_t row1)
{
	for (uint32_t y = row0; y < row1; y++) {
		for (uint32_t x = 0; x < IMG_W; x++) {
			float acc = 0.0f;
			for (int ky = -1; ky <= 1; ky++) {
				for (int kx = -1; kx <= 1; kx++) {
					const uint8_t *const px = PAD_AT(cur, (int)y + ky, (int)x + kx);
					for (uint32_t ic = 0; ic < CH; ic++)   /* compile-time CH so the accumulate loop unrolls */
						acc += ((float)px[ic] * dequant) *
						       (float)wf[ic * K * K +
								 (uint32_t)(ky + 1) * K + (uint32_t)(kx + 1)];
				}
			}
			int32_t o = round_half_up(128.0f + acc * FINAL_SCALE);
			if (o < 0) o = 0; else if (o > 255) o = 255;
			out[y * IMG_W + x] = (uint8_t)o;
		}
	}
}

#if DNCNN_REAL
/* Real conv_first: FP32 in_conv with bias, input x = image/255 (ZERO-padded like torch), ReLU,
 * quantize (times QUANT0 = 1/S0, round-to-nearest-even, clamp). Scalar accumulation in the SAME (oc; ky,kx)
 * order the numpy int8 reference uses, so the FP32 boundary is bit-faithful. */
static void conv_first_real(const uint8_t *restrict img, const float *restrict win,
			    const float *restrict bin, uint8_t *restrict qpad, float qscale,
			    uint32_t row0, uint32_t row1)
{
	for (uint32_t oc = 0; oc < CH; oc++) {
		for (uint32_t y = row0; y < row1; y++) {
			for (uint32_t x = 0; x < IMG_W; x++) {
				float acc = 0.0f;
				for (int ky = -1; ky <= 1; ky++) {
					const int yy = (int)y + ky;
					for (int kx = -1; kx <= 1; kx++) {
						const int xx = (int)x + kx;
						const float xv = (yy < 0 || yy >= (int)IMG_H || xx < 0 || xx >= (int)IMG_W)
							? 0.0f : (float)img[(uint32_t)yy * IMG_W + (uint32_t)xx] * (1.0f / 255.0f);
						acc += xv * win[oc * K * K + (uint32_t)(ky + 1) * K + (uint32_t)(kx + 1)];
					}
				}
				acc += bin[oc];
				int32_t q = rint_rne((acc > 0.0f ? acc : 0.0f) * qscale);
				if (q < 0) q = 0; else if (q > 255) q = 255;
				PAD_AT(qpad, (int)y, (int)x)[oc] = (uint8_t)q;
			}
		}
	}
}

/* Real conv_final: FP32 out_conv with bias over the dequantized last hidden activation (halo is
 * ZERO for real), then the residual: out = x + net(x), pixel = clip(round(255*(x + net))).
 * deepinv's DnCNN adds the predicted correction (out_conv(h)+x); net = out_conv(h)+bias.
 * Neighbours come from the zero halo, so no coord clamping. */
static void conv_final_real(const uint8_t *restrict cur, float dequant,
			    const float *restrict wout, float bout,
			    const uint8_t *restrict img, uint8_t *restrict out,
			    uint32_t row0, uint32_t row1)
{
	for (uint32_t y = row0; y < row1; y++) {
		for (uint32_t x = 0; x < IMG_W; x++) {
			float acc = 0.0f;
			for (int ky = -1; ky <= 1; ky++) {
				for (int kx = -1; kx <= 1; kx++) {
					const uint8_t *const px = PAD_AT(cur, (int)y + ky, (int)x + kx);
					for (uint32_t ic = 0; ic < CH; ic++)
						acc += ((float)px[ic] * dequant) *
						       wout[ic * K * K + (uint32_t)(ky + 1) * K + (uint32_t)(kx + 1)];
				}
			}
			acc += bout;
			const float xf = (float)img[y * IMG_W + x] * (1.0f / 255.0f);
			int32_t o = rint_rne(255.0f * (xf + acc));
			if (o < 0) o = 0; else if (o > 255) o = 255;
			out[y * IMG_W + x] = (uint8_t)o;
		}
	}
}
#endif  /* DNCNN_REAL */

/* Sum of the output bytes in rows [row0,row1). Each hart checksums its own band. */
static uint32_t stripe_checksum(const uint8_t *out, uint32_t row0, uint32_t row1)
{
	uint32_t sum = 0;
	for (uint32_t y = row0; y < row1; y++)
		for (uint32_t x = 0; x < IMG_W; x++)
			sum += out[y * IMG_W + x];
	return sum;
}

/* Re-arrange one hidden layer's weights from the blob's WH[oc][ic][k] into the FMA's group-major
 * A layout, matching pack_b_group's B order. Runs once per layer on hart 0. */
static void rearrange_hidden_weights(const int8_t *restrict W, int8_t *restrict aw_tap)
{
	uint32_t gidx = 0;
	for (uint32_t ky = 0; ky < K; ky++)
		for (uint32_t c = 0; c < K; c += FOLD_TAPS) {           /* one group per (ky, chunk) */
			const uint32_t nt = NT_AT(c);
			for (uint32_t oc = 0; oc < CH; oc++)
				for (uint32_t ti = 0; ti < nt; ti++)
					for (uint32_t ic = 0; ic < CH; ic++)
						/* line (g*CH+oc) packs the group's taps back-to-back at byte ti*CH+ic */
						aw_tap[((uint32_t)gidx * CH + oc) * ROW_STRIDE_BYTES + ti * CH + ic] =
							W[oc * CH * (K * K) + ic * (K * K) + (ky * K + c + ti)];
			gidx++;
		}
}

#ifdef DNCNN_DUMP
/* copy this hart's band of a padded buffer into a flat dump slot + evict it (debug only) */
static void dump_band(const uint8_t *restrict pad, uint8_t *restrict dst,
		      uint32_t row0, uint32_t row1)
{
	for (uint32_t y = row0; y < row1; y++)
		for (uint32_t x = 0; x < IMG_W; x++)
			for (uint32_t oc = 0; oc < CH; oc++)
				dst[(y * IMG_W + x) * CH + oc] = PAD_AT(pad, (int)y, (int)x)[oc];
	FENCE;
	evict(dst + (uint64_t)row0 * IMG_W * CH, (uint64_t)(row1 - row0) * IMG_W * CH);
	WAIT_CACHEOPS;
}
#endif

/* Run one int8 hidden layer over this hart's band: hart 0 builds the shared per-layer weights and
 * requant scale, all harts sync, then this hart tiles its band. */
static void run_hidden_layer(const uint8_t *restrict cur, uint8_t *restrict nxt,
			     const int8_t *restrict wh_layer, uint32_t hidden_idx,
			     int8_t *restrict aw_tap, float *restrict mvec,
			     const int32_t *restrict bias_hid_layer, int32_t *restrict bvec,
			     int8_t *restrict bpk, uint8_t *restrict temp,
			     uint32_t hart_id, uint32_t row0, uint32_t row1)
{
	(void)bias_hid_layer; (void)bvec;
	if (hart_id == 0u) {                              /* build the shared weights + scale (+ bias) */
		rearrange_hidden_weights(wh_layer, aw_tap);
		for (uint32_t oc = 0; oc < CH; oc++)
			mvec[oc] = DNCNN_REQUANT[hidden_idx];
#if DNCNN_REAL
		for (uint32_t oc = 0; oc < CH; oc++)
			bvec[oc] = bias_hid_layer[oc];       /* per-OC int32 bias for this layer */
#endif
		FENCE;
		evict(aw_tap, AW_TAP_BYTES);
		evict(mvec, MVEC_BYTES);
#if DNCNN_REAL
		evict(bvec, MVEC_BYTES);
#endif
		WAIT_CACHEOPS;
	}
	bench_barrier();                                 /* all harts wait for aw_tap/mvec/bvec in DRAM */

	invalidate_read(cur, row0, row1);                /* fresh neighbours, right before reading */
	for (uint32_t ty = row0; ty < row1; ty++)        /* my row band only */
		for (uint32_t tx = 0; tx < NTX; tx++)
			conv_tile(cur, aw_tap, bpk, mvec, bvec, temp, nxt, ty, tx * P);
	layer_publish(nxt, hart_id, row0, row1);
}

int main(uintptr_t arg_area)
{
	const uint32_t hart_id = bench_hart_id();
	if (!bench_hart_enabled(hart_id)) {
		return 0;
	}

	uint8_t *const base = (uint8_t *)buffer_base_from_args(arg_area);
	const uint8_t *const input   = base + INPUT_OFFSET;
	const uint8_t *const wblob   = base + WEIGHTS_OFFSET;
#if DNCNN_REAL
	/* mixed blob: FP32 in_conv W|b | int8 WH | int32 hidden biases | FP32 out_conv W|b */
	const float   *const win      = (const float   *)(wblob);
	const float   *const bin      = (const float   *)(wblob + WIN_BYTES);
	const int8_t  *const wh       = (const int8_t  *)(wblob + WIN_BYTES + BIN_BYTES);
	const int32_t *const bias_hid = (const int32_t *)(wblob + WIN_BYTES + BIN_BYTES + WH_BYTES);
	const float   *const wout     = (const float   *)(wblob + WIN_BYTES + BIN_BYTES + WH_BYTES + BHID_BYTES);
	const float          bout     = *(const float   *)(wblob + WIN_BYTES + BIN_BYTES + WH_BYTES + BHID_BYTES + WOUT_BYTES);
	int32_t *const bvec   = (int32_t *)(base + BVEC_OFFSET);    /* shared per-OC int32 bias (hart 0 builds) */
#else
	const int8_t  *const weights = (const int8_t *)wblob;
	const int8_t  *const w0      = weights;
	const int8_t  *const wh      = weights + W0_BYTES;
	const int8_t  *const wf      = weights + W0_BYTES + WH_BYTES;
#endif
	uint8_t *const output = base + OUTPUT_OFFSET;
	uint8_t *const qpadA  = base + QPADA_OFFSET;
	uint8_t *const qpadB  = base + QPADB_OFFSET;
	int8_t  *const aw_tap = (int8_t *)(base + AW_TAP_OFFSET);   /* shared (hart 0 builds) */
	float   *const mvec   = (float *)(base + MVEC_OFFSET);      /* shared (hart 0 builds) */
	int8_t  *const bpk    = (int8_t *)(base + BPACK_OFFSET + hart_id * BPK_STRIDE);   /* per-hart */
	uint8_t *const temp   = base + TEMP_OFFSET + hart_id * TEMP_STRIDE;               /* per-hart */
#ifdef DNCNN_DUMP
	uint8_t *const qdump  = base + QDUMP_OFFSET;
#endif
	volatile struct dncnn_slot *const slots =
		(volatile struct dncnn_slot *)(base + SLOTS_OFFSET);
	volatile struct dncnn_summary *const summary =
		(volatile struct dncnn_summary *)(base + SUMMARY_OFFSET);
	g_barrier = (volatile struct bench_barrier_state *)(base + BARRIER_OFFSET);

	/* this hart's row band [row0, row1) */
	const uint32_t row0 = (IMG_H * hart_id) / ACTIVE_HARTS;
	const uint32_t row1 = (IMG_H * (hart_id + 1u)) / ACTIVE_HARTS;

#ifdef DNCNN_PMC
	pmc_probe_begin(base + PMC_OFFSET, hart_id, ACTIVE_HARTS);
#endif

	/* Iterate the shape descriptor: conv_first, then the hidden stack, then conv_final. The
	 * hidden layers ping-pong between qpadA/qpadB; the FP32 boundaries fold in quant/dequant. */
	struct layer_cfg net[LAYERS];
	build_net(net);
	uint8_t *cur = qpadA;   /* conv_first writes here, then hidden layers consume/produce */
	uint8_t *nxt = qpadB;
	uint32_t hidden_idx = 0;
#ifdef DNCNN_DUMP
	uint32_t dump_idx = 0;
#endif

	for (uint32_t l = 0; l < LAYERS; l++) {
		const struct layer_cfg lc = net[l];

		if (lc.kind == FP32_FIRST) {
			/* conv_first + quantize -> cur band, then publish it across harts */
#if DNCNN_REAL
			conv_first_real(input, win, bin, cur, DNCNN_QUANT0, row0, row1);
#else
			conv_first_quant(input, w0, cur, DNCNN_QUANT0, row0, row1);
#endif
#ifdef DNCNN_DUMP
			dump_band(cur, qdump + (dump_idx++) * ACT_BYTES, row0, row1);
#endif
			layer_publish(cur, hart_id, row0, row1);

		} else if (lc.kind == INT8_HIDDEN) {
			run_hidden_layer(cur, nxt, wh + hidden_idx * CH * CH * (K * K), hidden_idx,
					 aw_tap, mvec,
#if DNCNN_REAL
					 bias_hid + hidden_idx * CH, bvec,
#else
					 (const int32_t *)0, (int32_t *)0,
#endif
					 bpk, temp, hart_id, row0, row1);
#ifdef DNCNN_DUMP
			dump_band(nxt, qdump + (dump_idx++) * ACT_BYTES, row0, row1);
#endif
			uint8_t *const t = cur; cur = nxt; nxt = t;   /* ping-pong */
			hidden_idx++;

		} else {  /* FP32_FINAL */
			/* conv_final + dequant, reads the synced activation directly -> output */
			invalidate_read(cur, row0, row1);
#if DNCNN_REAL
			conv_final_real(cur, DNCNN_DEQUANT3, wout, bout, input, output, row0, row1);
#else
			conv_final_dequant(cur, DNCNN_DEQUANT3, wf, output, row0, row1);
#endif
		}
	}

	FENCE;
	evict(output + (uint64_t)row0 * IMG_W, (uint64_t)(row1 - row0) * IMG_W);   /* my band */
	WAIT_CACHEOPS;
	bench_barrier();   /* whole output image in DRAM before anyone checksums it */

#ifdef DNCNN_PMC
	pmc_probe_end(base + PMC_OFFSET, hart_id);
#endif

	/* Attest this hart's band: publish a slot with the band checksum, so hart 0 can
	 * fold them and cross-check against a fresh whole-image sum (the CI correctness gate). */
	volatile struct dncnn_slot *const my_slot = &slots[hart_id];
	my_slot->magic        = DNCNN_MAGIC;
	my_slot->hart_id      = hart_id;
	my_slot->minion_id    = get_minion_id();
	my_slot->thread_id    = get_thread_id();
	my_slot->row0         = row0;
	my_slot->row1         = row1;
	my_slot->active_harts = ACTIVE_HARTS;
	my_slot->checksum     = stripe_checksum(output, row0, row1);
	my_slot->done         = 1u;
	FENCE;
	evict((const void *)my_slot, sizeof(*my_slot));
	WAIT_CACHEOPS;
	bench_barrier();   /* all slots in DRAM before hart 0 reads them */

	if (hart_id == 0u) {
		uint32_t active_mask = 0u, done_count = 0u, slot_checksum_sum = 0u, output_sum = 0u;
		for (uint32_t h = 0; h < ACTIVE_HARTS; h++) {
			if (slots[h].magic == DNCNN_MAGIC && slots[h].done == 1u) {
				done_count++;
				active_mask |= 1u << slots[h].hart_id;
				slot_checksum_sum += slots[h].checksum;
			}
		}
		for (uint32_t i = 0; i < IMG_BYTES; i++)
			output_sum += output[i];

		const uint64_t macs = (uint64_t)IMG_W * IMG_H *
			((uint64_t)CH * K * K + (uint64_t)HIDDEN * CH * CH * K * K + (uint64_t)CH * K * K);
		const uint64_t ops = macs * 2u;   /* one pass; multiply + add */

		/* runtime cross-check: the descriptor must mirror the compile-time shape macros */
		uint32_t net_hidden = 0u, shape_ok = 1u;
		for (uint32_t l = 0; l < LAYERS; l++) {
			if (net[l].kind == INT8_HIDDEN) {
				net_hidden++;
				if (net[l].in_ch != CH || net[l].out_ch != CH) shape_ok = 0u;
			}
		}
		if (net_hidden != HIDDEN) shape_ok = 0u;

		summary->magic             = DNCNN_MAGIC;
		summary->active_harts      = ACTIVE_HARTS;
		summary->passes            = 1u;
		summary->width             = IMG_W;
		summary->height            = IMG_H;
		summary->channels          = CH;
		summary->layers            = LAYERS;
		summary->active_mask       = active_mask;
		summary->done_count        = done_count;
		summary->output_sum        = output_sum;
		summary->slot_checksum_sum = slot_checksum_sum;
		summary->ops_lo            = (uint32_t)ops;
		summary->ops_hi            = (uint32_t)(ops >> 32);
		summary->tensor_error      = (uint32_t)get_tensor_error() | (shape_ok ? 0u : 0x80000000u);
		FENCE;
		evict((const void *)summary, sizeof(*summary));
		WAIT_CACHEOPS;
	}

	return 0;
}
