"""Generate the INT8 mixed-precision reference + scales for the DnCNN M3 kernel.

Reuses the synthetic input/weights and the FP32 conv_first/conv_hidden/conv_final
from gen_dncnn_inputs.py (same seed => identical input/weights blobs). Adds the
int8 hidden-layer path (uint8 activations x int8 weights -> int32 -> requant):

  conv_first (FP32) -> quantize -> hidden1/2/3 (int8) -> dequantize -> conv_final (FP32)

Emits (into the same OUT dir as gen_dncnn_inputs.py):
  - dncnn_reference_int8.npy : what the int8 kernel must produce  (DEV gate, max_abs<=1)
  - dncnn_int8_scales.h      : per-layer quant/requant/dequant scales the kernel #includes

And prints the FP32-vs-int8 accuracy (the REAL quality gate: quantization must stay
close to the FP32 output, else the scheme -- not the gate -- has to change).

Run: python3 ported_models/dncnn/scripts/gen_dncnn_int8.py
"""
import numpy as np
from gen_dncnn_inputs import (IMG_W, IMG_H, CH, HIDDEN_SCALE, OUT,
                              make_input, make_weights,
                              conv_first, conv_hidden, conv_final, host_reference)

def conv_hidden_acc_i32(qact, Wl):
    """int8 hidden conv accumulator: qact uint8 [H,W,CH], Wl int8 (oc,ic,k) -> int32 [H,W,CH]."""
    xp = np.pad(qact.astype(np.int32), ((1, 1), (1, 1), (0, 0)), mode='edge')
    acc = np.zeros((IMG_H, IMG_W, CH), dtype=np.int64)
    for oc in range(CH):
        a = np.zeros((IMG_H, IMG_W), dtype=np.int64)
        for ky in range(-1, 2):
            for kx in range(-1, 2):
                k = (ky + 1) * 3 + (kx + 1)
                window = xp[1 + ky:1 + ky + IMG_H, 1 + kx:1 + kx + IMG_W, :]
                a += (window * Wl[oc, :, k].astype(np.int64)).sum(axis=2)
        acc[:, :, oc] = a
    assert np.abs(acc).max() < 2**31, "int32 overflow in hidden acc"
    return acc.astype(np.int32)

def requant_u8(acc_i32, M):
    """int32 acc -> uint8: x per-tensor M, round-nearest-even, ReLU+clamp [0,255]."""
    return np.clip(np.rint(acc_i32.astype(np.float32) * np.float32(M)), 0, 255).astype(np.uint8)

def host_reference_int8(img, W0, WH, WF):
    act0 = conv_first(img, W0)                               # FP32 [H,W,CH]
    a1 = conv_hidden(act0, WH[0]); a2 = conv_hidden(a1, WH[1]); a3 = conv_hidden(a2, WH[2])
    # per-tensor activation scales, calibrated from FP32 ranges (max -> 255)
    S = [float(a.max()) / 255.0 for a in (act0, a1, a2, a3)]
    # folded per-layer requant multiplier M_l = S_in * HIDDEN_SCALE / S_out
    M = [S[l] * HIDDEN_SCALE / S[l + 1] for l in range(3)]
    # int8 forward using the fixed scales (this is exactly what the kernel does)
    q0 = np.clip(np.rint(act0 / np.float32(S[0])), 0, 255).astype(np.uint8)
    acc0 = conv_hidden_acc_i32(q0, WH[0]); q1 = requant_u8(acc0, M[0])
    acc1 = conv_hidden_acc_i32(q1, WH[1]); q2 = requant_u8(acc1, M[1])
    acc2 = conv_hidden_acc_i32(q2, WH[2]); q3 = requant_u8(acc2, M[2])
    act3_deq = q3.astype(np.float32) * np.float32(S[3])      # dequant for FP32 conv_final
    out = conv_final(act3_deq, WF)
    return out, dict(S=S, M=M, q=[q0, q1, q2, q3])

def write_int8_scales_h(S, M, path):
    with open(path, "w") as f:
        f.write("/* auto-generated by gen_dncnn_int8.py -- int8 mixed-precision scales */\n")
        f.write("#ifndef DNCNN_INT8_SCALES_H\n#define DNCNN_INT8_SCALES_H\n")
        f.write(f"static const float DNCNN_QUANT0     = {1.0/S[0]:.9g}f;  /* conv_first FP32 -> uint8 */\n")
        f.write(f"static const float DNCNN_REQUANT[3] = {{ {M[0]:.9g}f, {M[1]:.9g}f, {M[2]:.9g}f }};\n")
        f.write(f"static const float DNCNN_DEQUANT3   = {S[3]:.9g}f;  /* uint8 -> FP32 for conv_final */\n")
        f.write("#endif\n")

def main():
    rng = np.random.default_rng(0)                # SAME seed as gen_dncnn_inputs
    OUT.mkdir(parents=True, exist_ok=True)
    img = make_input(rng); W0, WH, WF = make_weights(rng)

    ref_fp = host_reference(img, W0, WH, WF)               # FP32-path uint8 (quality anchor)
    ref_i8, st = host_reference_int8(img, W0, WH, WF)      # int8-path uint8 (dev gate)
    S, M = st['S'], st['M']

    np.save(OUT / "dncnn_reference_int8.npy", ref_i8)
    write_int8_scales_h(S, M, OUT / "dncnn_int8_scales.h")

    d = np.abs(ref_i8.astype(int) - ref_fp.astype(int))    # int8 vs FP32 = quantization error
    print("scales S   =", [round(s, 4) for s in S])
    print("requant M  =", [f"{m:.3e}" for m in M],
          f" quant0={1/S[0]:.4g} dequant3={S[3]:.4g}")
    for i, q in enumerate(st['q']):
        print(f"  q{i}: clip255={int((q==255).sum())} zeros={int((q==0).sum())} "
              f"mid={int(((q>0)&(q<255)).sum())}")
    print("int8 ref   :", ref_i8.shape, "min", int(ref_i8.min()), "max", int(ref_i8.max()),
          "std", round(float(ref_i8.std()), 1))
    print(f"ACCURACY int8-vs-FP32: max_abs={d.max()}  mean_abs={d.mean():.3f}  "
          f"frac>1={100*(d>1).mean():.2f}%   (real quality gate)")

if __name__ == "__main__":
    main()
